<?xml version="1.0" encoding="UTF-8"?>
<!--
This file was generated by Altova MapForce 2015r4

YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.

Refer to the Altova MapForce Documentation for further details.
http://www.altova.com/mapforce
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:agt="http://www.altova.com/Mapforce/agt" xmlns:xs="http://www.w3.org/2001/XMLSchema" exclude-result-prefixes="agt xs">
	<xsl:output method="xml" encoding="UTF-8" indent="yes"/>
	<xsl:template name="agt:MapTopiwind_modelloc_var5_create_rec">
		<xsl:param name="var4_current"/>
		<rec>
			<xsl:variable name="var1_ROWID">
				<xsl:if test="$var4_current/@ROW_ID">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var1_ROWID))) != 'false'">
				<xsl:attribute name="ID">
					<xsl:value-of select="string($var4_current/@ROW_ID)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var2_LATITUDE">
				<xsl:if test="$var4_current/@LATITUDE">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var2_LATITUDE))) != 'false'">
				<xsl:attribute name="LAT">
					<xsl:value-of select="string($var4_current/@LATITUDE)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var3_LONGITUDE">
				<xsl:if test="$var4_current/@LONGITUDE">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var3_LONGITUDE))) != 'false'">
				<xsl:attribute name="LON">
					<xsl:value-of select="string($var4_current/@LONGITUDE)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:attribute name="COVERAGE">1</xsl:attribute>
			<xsl:attribute name="CLASS_1">R</xsl:attribute>
			<xsl:attribute name="CLASS_2">R</xsl:attribute>
		</rec>
	</xsl:template>
	<xsl:template name="agt:MapTopiwind_modelloc_var7_resultof_map">
		<xsl:param name="var6_current"/>
		<xsl:for-each select="$var6_current/rec">
			<xsl:call-template name="agt:MapTopiwind_modelloc_var5_create_rec">
				<xsl:with-param name="var4_current" select="."/>
			</xsl:call-template>
		</xsl:for-each>
	</xsl:template>
	<xsl:template match="/">
		<root>
			<xsl:attribute name="xsi:noNamespaceSchemaLocation" namespace="http://www.w3.org/2001/XMLSchema-instance">C:/Users/Administrator/Desktop/git/PiWind/piwind_modelloc.xsd</xsl:attribute>
			<xsl:for-each select="root">
				<xsl:call-template name="agt:MapTopiwind_modelloc_var7_resultof_map">
					<xsl:with-param name="var6_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
		</root>
	</xsl:template>
</xsl:stylesheet>
