__all__ = [
    'SUMMARY_LEVEL_LOC',
    'SUMMARY_LEVEL_ACC',
    'OED_LOCATION_COLS',
    'OED_ACCOUNT_COLS',
    'OED_REINSINFO_COLS',
    'OED_REINSSCOPE_COLS',
]

SUMMARY_LEVEL_LOC = [
 'accnumber',
 'areacode',
 'areaname',
 'basement',
 'city',
 'condnumber',
 'condpriority',
 'constructioncode',
 'correlationgroup',
 'countrycode',
 'geogname1',
 'geogname2',
 'geogname3',
 'geogname4',
 'geogname5',
 'geogscheme1',
 'geogscheme2',
 'geogscheme3',
 'geogscheme4',
 'geogscheme5',
 'locgroup',
 'locname',
 'locnumber',
 'locperilscovered',
 'locuserdef1',
 'locuserdef2',
 'locuserdef3',
 'locuserdef4',
 'locuserdef5',
 'numberofstoreys',
 'occupancycode',
 'portnumber',
 'postalcode']

SUMMARY_LEVEL_ACC = [
 'accgroup',
 'accname',
 'accnumber',
 'accuserdef1',
 'accuserdef2',
 'accuserdef3',
 'accuserdef4',
 'accuserdef5',
 'cedantname',
 'condname',
 'condnumber',
 'lob',
 'polnumber',
 'poluserdef1',
 'poluserdef2',
 'poluserdef3',
 'poluserdef4',
 'poluserdef5',
 'portname',
 'portnumber']

OED_LOCATION_COLS = {'PortNumber': {'desc': 'Portfolio number',
  'require_field': 'R',
  'data_type': 'varchar(20)',
  'default_value': "n/a"},
 'AccNumber': {'desc': 'Account number',
  'require_field': 'R',
  'data_type': 'nvarchar(40)',
  'default_value': "n/a"},
 'LocNumber': {'desc': 'Location number',
  'require_field': 'R',
  'data_type': 'nvarchar(20)',
  'default_value': "n/a"},
 'LocName': {'desc': 'Location name',
  'require_field': 'O',
  'data_type': 'nvarchar(20)',
  'default_value': "n/a"},
 'LocGroup': {'desc': 'Location group name',
  'require_field': 'O',
  'data_type': 'nvarchar(20)',
  'default_value': "n/a"},
 'CorrelationGroup': {'desc': 'Correlation Group: indicates which locations should be correlated between each other in Oasis LMF.',
  'require_field': 'O',
  'data_type': 'int',
  'default_value': "n/a"},
 'IsPrimary': {'desc': 'Whether the location in LocGroup is the primary building in the group',
  'require_field': 'O',
  'data_type': '0 or 1',
  'default_value': '1'},
 'IsTenant': {'desc': 'Whether property is occupied by a tenant or not',
  'require_field': 'O',
  'data_type': '0 or 1',
  'default_value': '0'},
 'BuildingID': {'desc': 'Unique building identification number',
  'require_field': 'O',
  'data_type': 'int',
  'default_value': "n/a"},
 'LocInceptionDate': {'desc': 'Location inception date - DD/MM/YYYY format',
  'require_field': 'O',
  'data_type': 'smalldatetime',
  'default_value': "n/a"},
 'LocExpiryDate': {'desc': 'Location expiry date - DD/MM/YYYY format',
  'require_field': 'O',
  'data_type': 'smalldatetime',
  'default_value': "n/a"},
 'PercentComplete': {'desc': 'Completeness percentage of the construction project at this location. The project completion percentage is by the cost of the project. Values between 0 to 1 (e.g. 12% enterd as 0.12)',
  'require_field': 'O',
  'data_type': 'decimal',
  'default_value': '1'},
 'CompletionDate': {'desc': 'Construction project completion date - DD/MM/YYYY format',
  'require_field': 'O',
  'data_type': 'date',
  'default_value': "n/a"},
 'CountryCode': {'desc': 'Country code (based on ISO3166 alpha-2 codes)',
  'require_field': 'R',
  'data_type': 'char(2)',
  'default_value': "n/a"},
 'Latitude': {'desc': 'Latitude in degrees (-90.0 to +90.0)',
  'require_field': 'O',
  'data_type': 'decimal',
  'default_value': '0'},
 'Longitude': {'desc': 'Longitude in degrees (-180.0 to +180.0)',
  'require_field': 'O',
  'data_type': 'decimal',
  'default_value': '0'},
 'StreetAddress': {'desc': 'Street address including house number ',
  'require_field': 'O',
  'data_type': 'nvarchar(100)',
  'default_value': "n/a"},
 'PostalCode': {'desc': 'Postcode: the highest resolution postcode most often used. (e.g. 5 digit zip for the US).',
  'require_field': 'O',
  'data_type': 'nvarchar(20)',
  'default_value': "n/a"},
 'City': {'desc': 'City',
  'require_field': 'O',
  'data_type': 'nvarchar(50)',
  'default_value': "n/a"},
 'AreaCode': {'desc': 'Code representing typically the largest sub-division in a country (e.g. State code). See AreaCode Values sheet for details.',
  'require_field': 'O',
  'data_type': 'nvarchar(20)',
  'default_value': "n/a"},
 'AreaName': {'desc': 'Name relating to the AreaCode (e.g. State name). See AreaCode Values sheet for details.',
  'require_field': 'O',
  'data_type': 'nvarchar(50)',
  'default_value': "n/a"},
 'GeogScheme1': {'desc': "Geography scheme: Descriptor of the geography scheme used in relation to the geography name in the corresponding GeogName field (e.g. PC4). User can specify values in addition to those listed in the GeogScheme values list, but user defined scheme values must start with 'X'.",
  'require_field': 'O',
  'data_type': 'varchar(5)',
  'default_value': "n/a"},
 'GeogName1': {'desc': 'Geography name: Descriptor of the geographical area, using the scheme referenced in the corresponding GeogScheme field (e.g. SO31)',
  'require_field': 'O',
  'data_type': 'nvarchar(50)',
  'default_value': "n/a"},
 'GeogScheme2': {'desc': "Geography scheme: Descriptor of the geography scheme used in relation to the geography name in the corresponding GeogName field (e.g. PC4). User can specify values in addition to those listed in the GeogScheme values list, but user defined scheme values must start with 'X'.",
  'require_field': 'O',
  'data_type': 'varchar(5)',
  'default_value': "n/a"},
 'GeogName2': {'desc': 'Geography name: Descriptor of the geographical area, using the scheme referenced in the corresponding GeogScheme field (e.g. SO31)',
  'require_field': 'O',
  'data_type': 'nvarchar(50)',
  'default_value': "n/a"},
 'GeogScheme3': {'desc': "Geography scheme: Descriptor of the geography scheme used in relation to the geography name in the corresponding GeogName field (e.g. PC4). User can specify values in addition to those listed in the GeogScheme values list, but user defined scheme values must start with 'X'.",
  'require_field': 'O',
  'data_type': 'varchar(5)',
  'default_value': "n/a"},
 'GeogName3': {'desc': 'Geography name: Descriptor of the geographical area, using the scheme referenced in the corresponding GeogScheme field (e.g. SO31)',
  'require_field': 'O',
  'data_type': 'nvarchar(50)',
  'default_value': "n/a"},
 'GeogScheme4': {'desc': "Geography scheme: Descriptor of the geography scheme used in relation to the geography name in the corresponding GeogName field (e.g. PC4). User can specify values in addition to those listed in the GeogScheme values list, but user defined scheme values must start with 'X'.",
  'require_field': 'O',
  'data_type': 'varchar(5)',
  'default_value': "n/a"},
 'GeogName4': {'desc': 'Geography name: Descriptor of the geographical area, using the scheme referenced in the corresponding GeogScheme field (e.g. SO31)',
  'require_field': 'O',
  'data_type': 'nvarchar(50)',
  'default_value': "n/a"},
 'GeogScheme5': {'desc': "Geography scheme: Descriptor of the geography scheme used in relation to the geography name in the corresponding GeogName field (e.g. PC4). User can specify values in addition to those listed in the GeogScheme values list, but user defined scheme values must start with 'X'.",
  'require_field': 'O',
  'data_type': 'varchar(5)',
  'default_value': "n/a"},
 'GeogName5': {'desc': 'Geography name: Descriptor of the geographical area, using the scheme referenced in the corresponding GeogScheme field (e.g. SO31)',
  'require_field': 'O',
  'data_type': 'nvarchar(50)',
  'default_value': "n/a"},
 'AddressMatch': {'desc': 'Address match from geocoder: indicating the resolution that the latitude / longitude represents',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'GeocodeQuality': {'desc': 'Geocode quality (values between 0 and 1 e.g. 80% is entered as 0.8)',
  'require_field': 'O',
  'data_type': 'float',
  'default_value': "n/a"},
 'Geocoder': {'desc': 'Company name / version of geocoder. Free text field.',
  'require_field': 'O',
  'data_type': 'varchar(20)',
  'default_value': "n/a"},
 'OrgOccupancyScheme': {'desc': 'Original occupancy scheme',
  'require_field': 'O',
  'data_type': 'varchar(10)',
  'default_value': "n/a"},
 'OrgOccupancyCode': {'desc': 'Original occupancy code',
  'require_field': 'O',
  'data_type': 'varchar(100)',
  'default_value': "n/a"},
 'OrgConstructionScheme': {'desc': 'Original construction scheme',
  'require_field': 'O',
  'data_type': 'varchar(10)',
  'default_value': "n/a"},
 'OrgConstructionCode': {'desc': 'Original construction code',
  'require_field': 'O',
  'data_type': 'varchar(100)',
  'default_value': "n/a"},
 'OccupancyCode': {'desc': 'OED occupancy code',
  'require_field': 'O',
  'data_type': 'int',
  'default_value': '1000'},
 'ConstructionCode': {'desc': 'OED construction code',
  'require_field': 'O',
  'data_type': 'int',
  'default_value': '5000'},
 'YearBuilt': {'desc': 'Year built (4 digit year)',
  'require_field': 'O',
  'data_type': 'smallint',
  'default_value': '0'},
 'NumberOfStoreys': {'desc': 'Number of storeys',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'NumberOfBuildings': {'desc': 'Number of buildings',
  'require_field': 'O',
  'data_type': 'int',
  'default_value': '1'},
 'FloorArea': {'desc': 'Floor area: the total area across all floors',
  'require_field': 'O',
  'data_type': 'float',
  'default_value': '0'},
 'FloorAreaUnit': {'desc': 'Units in which FloorArea is specified',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '11'},
 'LocUserDef1': {'desc': 'Location user defined field 1',
  'require_field': 'O',
  'data_type': 'varchar(20)',
  'default_value': "n/a"},
 'LocUserDef2': {'desc': 'Location user defined field 2',
  'require_field': 'O',
  'data_type': 'varchar(20)',
  'default_value': "n/a"},
 'LocUserDef3': {'desc': 'Location user defined field 3',
  'require_field': 'O',
  'data_type': 'varchar(20)',
  'default_value': "n/a"},
 'LocUserDef4': {'desc': 'Location user defined field 4',
  'require_field': 'O',
  'data_type': 'varchar(20)',
  'default_value': "n/a"},
 'LocUserDef5': {'desc': 'Location user defined field 5',
  'require_field': 'O',
  'data_type': 'varchar(20)',
  'default_value': "n/a"},
 'FlexiLocZZZ': {'desc': 'Flexible field that is stored in FlexiLoc table in ModifierName = ZZZ',
  'require_field': 'O',
  'data_type': 'varchar(40)',
  'default_value': "n/a"},
 'LocPerilsCovered': {'desc': 'Location perils covered',
  'require_field': 'R',
  'data_type': 'varchar(250)',
  'default_value': "n/a"},
 'BuildingTIV': {'desc': 'Building Total Insured Value',
  'require_field': 'R',
  'data_type': 'float',
  'default_value': "n/a"},
 'OtherTIV': {'desc': 'Other Building Insured Value (primarily aimed at specific US policies)',
  'require_field': 'R',
  'data_type': 'float',
  'default_value': "n/a"},
 'ContentsTIV': {'desc': 'Contents Total Insured Value',
  'require_field': 'R',
  'data_type': 'float',
  'default_value': "n/a"},
 'BITIV': {'desc': 'Business Interruption (BI) Total Insured Value',
  'require_field': 'R',
  'data_type': 'float',
  'default_value': "n/a"},
 'BIPOI': {'desc': 'BI period of indemnity (in days, in increments of 0.5 days). Default value = 365 (1 year).',
  'require_field': 'O',
  'data_type': 'float',
  'default_value': '365'},
 'LocCurrency': {'desc': 'Location currency',
  'require_field': 'R',
  'data_type': 'char(3)',
  'default_value': "n/a"},
 'LocGrossPremium': {'desc': 'Gross premium amount at location level',
  'require_field': 'O',
  'data_type': 'float',
  'default_value': '0'},
 'LocTax': {'desc': 'Insurance tax amount at location level',
  'require_field': 'O',
  'data_type': 'float',
  'default_value': '0'},
 'LocBrokerage': {'desc': 'Brokerage amount at location level',
  'require_field': 'O',
  'data_type': 'float',
  'default_value': '0'},
 'LocNetPremium': {'desc': 'Net premium at location level',
  'require_field': 'O',
  'data_type': 'float',
  'default_value': '0'},
 'NonCatGroundUpLoss': {'desc': 'Ground-Up non-cat loss value prior to the application of non-cat policy terms',
  'require_field': 'O',
  'data_type': 'float',
  'default_value': '0'},
 'LocParticipation': {'desc': 'Percentage of risk that the insurer covers for this location. Values between 0 to 1 (e.g. 12% enterd as 0.12). Usually used in binders or offshore.',
  'require_field': 'O',
  'data_type': 'float',
  'default_value': '1'},
 'PayoutBasis': {'desc': 'Pay-out basis for the claim (whether depreciation is taken into account). ACV = RCV - depreciation.',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'ReinsTag': {'desc': 'User defined reinsurance tag to provide a further option for specifying reinsurance scope',
  'require_field': 'O',
  'data_type': 'varchar(20)',
  'default_value': "n/a"},
 'CondNumber': {'desc': 'Condition Number to be able to link to relevant special condition (numbers only). Matches with CondNumber in Acc file.',
  'require_field': 'CR',
  'data_type': 'int',
  'default_value': "n/a"},
 'CondPriority': {'desc': 'Condition priority: specifies the order in which special conditions apply if multiple conditions apply to one location.',
  'require_field': 'CR',
  'data_type': 'int',
  'default_value': "n/a"},
 'LocDedCode1Building': {'desc': 'Location building deductible code',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'LocDedType1Building': {'desc': 'Location building deductible type',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'LocDed1Building': {'desc': 'Location building deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'LocMinDed1Building': {'desc': 'Location minimum building deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'LocMaxDed1Building': {'desc': 'Location maximum building deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'LocDedCode2Other': {'desc': 'Location other building deductible code',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'LocDedType2Other': {'desc': 'Location other building deductible type',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'LocDed2Other': {'desc': 'Location other building deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'LocMinDed2Other': {'desc': 'Location minimum other building deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'LocMaxDed2Other': {'desc': 'Location maximum other building deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'LocDedCode3Contents': {'desc': 'Location contents deductible code',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'LocDedType3Contents': {'desc': 'Location contents deductible type',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'LocDed3Contents': {'desc': 'Location contents deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'LocMinDed3Contents': {'desc': 'Location minimum contents deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'LocMaxDed3Contents': {'desc': 'Location maximum contents deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'LocDedCode4BI': {'desc': 'Location BI Deductible Code',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'LocDedType4BI': {'desc': 'Location BI Deductible Type',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'LocDed4BI': {'desc': 'Location BI deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'LocMinDed4BI': {'desc': 'Location minimum bi deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'LocMaxDed4BI': {'desc': 'Location maximum bi deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'LocDedCode5PD': {'desc': 'Location PD deductible code',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'LocDedType5PD': {'desc': 'Location PD deductible type',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'LocDed5PD': {'desc': 'Location PD deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'LocMinDed5PD': {'desc': 'Location minimum PD deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'LocMaxDed5PD': {'desc': 'Location maximum PD deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'LocDedCode6All': {'desc': 'Location blanket deductible code',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'LocDedType6All': {'desc': 'Location blanket deductible type',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'LocDed6All': {'desc': 'Location site deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'LocMinDed6All': {'desc': 'Location minimum blanket deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'LocMaxDed6All': {'desc': 'Location maximum blanket deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'LocLimitCode1Building': {'desc': 'Location building limit code',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'LocLimitType1Building': {'desc': 'Location building limit type',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'LocLimit1Building': {'desc': 'Location building limit',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'LocLimitCode2Other': {'desc': 'Location other building limit code',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'LocLimitType2Other': {'desc': 'Location other building limit type',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'LocLimit2Other': {'desc': 'Location other building limit',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'LocLimitCode3Contents': {'desc': 'Location contents limit code',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'LocLimitType3Contents': {'desc': 'Location contents limit type',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'LocLimit3Contents': {'desc': 'Location contents limit',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'LocLimitCode4BI': {'desc': 'Location BI limit code',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'LocLimitType4BI': {'desc': 'Location BI limit type',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'LocLimit4BI': {'desc': 'Location BI limit',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'LocLimitCode5PD': {'desc': 'Location PD limit code',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'LocLimitType5PD': {'desc': 'Location PD limit type',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'LocLimit5PD': {'desc': 'Location PD limit',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'LocLimitCode6All': {'desc': 'Location site limit code',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'LocLimitType6All': {'desc': 'Location site limit type',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'LocLimit6All': {'desc': 'Location site limit',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'BIWaitingPeriod': {'desc': 'BI waiting period (in days)',
  'require_field': 'O',
  'data_type': 'smallint',
  'default_value': '0'},
 'LocPeril': {'desc': 'Perils for location financial terms',
  'require_field': 'CR',
  'data_type': 'varchar(250)',
  'default_value': "n/a"},
 'YearUpgraded': {'desc': 'Year the building was upgraded (4 digit year)',
  'require_field': 'O',
  'data_type': 'smallint',
  'default_value': '0'},
 'SurgeLeakage': {'desc': 'Storm leakage percentage (0% to 100%) for Wind only policies',
  'require_field': 'O',
  'data_type': 'float',
  'default_value': '-999'},
 'SprinklerType': {'desc': 'Sprinkler type',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'PercentSprinklered': {'desc': 'Percent sprinklered. Values between 0 and 1 inclusive (0.5 = 50%); -999 is unknown',
  'require_field': 'O',
  'data_type': 'float',
  'default_value': '-999'},
 'RoofCover': {'desc': 'Code that represents the material used to cover the roof',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'RoofYearBuilt': {'desc': 'Year the roof was last replaced (4 digit year)',
  'require_field': 'O',
  'data_type': 'smallint',
  'default_value': '0'},
 'RoofGeometry': {'desc': 'Code that represents the shape of the roof',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'RoofEquipment': {'desc': 'captures if mechanical or electric equipment is braced on the roof and the impact this modifier will have on the losses.',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'RoofFrame': {'desc': 'Roof framing material',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'RoofMaintenance': {'desc': 'Captures the impact roof maintenance has on the losses',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'BuildingCondition': {'desc': 'Building condition',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'RoofAttachedStructures': {'desc': 'Code that identifies items mounted on the roof, such as A/C units, skylights, or dormers',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'RoofDeck': {'desc': 'Code that represents the materials used to construct the roof deck',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'RoofPitch': {'desc': 'Code that represents the slope of the roof',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'RoofAnchorage': {'desc': 'Code that represents the connections used to secure the roof support system to the walls',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'RoofDeckAttachment': {'desc': 'Code that represents the connections used to secure the roof deck to the underlying roof support system',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'RoofCoverAttachment': {'desc': 'Code that represents the connections used to secure the roof covering to the roof deck',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'GlassType': {'desc': 'Code that represents the type of glass used in the building',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'LatticeType': {'desc': 'Code that represents the type of web used for H-shaped steel',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'FloodZone': {'desc': 'Flood zone. Free text field.',
  'require_field': 'O',
  'data_type': 'varchar(20)',
  'default_value': "n/a"},
 'SoftStory': {'desc': 'Code that indicates if there is structural weakness at any floor.  First floor garages and taller first floors are likely to exhibit soft-story behaviour.',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'Basement': {'desc': 'Code that defines if there is a basement and if so whether it is finished or unfinished',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'BasementLevelCount': {'desc': 'Indicates the number of basement levels in a structure (supports up to 5 levels; for more than 5, enter 5).',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'WindowProtection': {'desc': 'Code that represents the wind protection systems used on the windows',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'FoundationType': {'desc': "Code that represents the construction type of the building's foundation",
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'WallAttachedStructure': {'desc': ' \nCode that represents a structure that is physically attached to the building, such as garage or balcony',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'AppurtenantStructure': {'desc': ' \nCode for the appurtenant building, such as shed or detached garage',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'ConstructionQuality': {'desc': 'Construction quality',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'GroundEquipment': {'desc': 'Captures whether mechanical or electrical equipment are present on the ground level of a building and impact it has on losses',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'EquipmentBracing': {'desc': 'Identifies where mechanical or electrical equipment is held in place by bracing',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'Flashing': {'desc': 'Refers to the impact the quality of the flashing or coping on a roof has on losses',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'BuildingShape': {'desc': 'Code that represents the shape of the building',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'ShapeIrregularity': {'desc': 'Identifies vertical irregularities, overhangs and setbacks in the building design',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'Pounding': {'desc': 'Code that represents the distance to the closest structure, which if not adequate, can cause the two structures to collide during earthquake shaking',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'Ornamentation': {'desc': 'Code that represents the amount of decorative elements attached to the exterior of a building',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'SpecialEQConstruction': {'desc': 'Presence of a seismic base isolation system',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'Retrofit': {'desc': 'Presence of retro fit connectivity between walls and floor for retro fit buildings',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'CrippleWall': {'desc': 'Presence of cripple walls on the first floor or frame buildings',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'FoundationConnection': {'desc': 'Connection of frame to foundation with or without bolts',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'ShortColumn': {'desc': 'Code that indicates if there are short columns in the building',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'Fatigue': {'desc': 'Captures signs of damage from prior earthquakes',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'Cladding': {'desc': 'The presence and material of exterior building cladding',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'BIPreparedness': {'desc': 'BI preparedness',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'BIRedundancy': {'desc': 'BI redundancy',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'FirstFloorHeight': {'desc': 'Height of the lowest floor (above ground) of the building with respect to local ground elevation (NOT relative to datum). First floor in the US is identical to ground floor in Europe.',
  'require_field': 'O',
  'data_type': 'float',
  'default_value': '-999'},
 'FirstFloorHeightUnit': {'desc': 'Code for the unit of measure used to express FirstFloorHeight',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '1'},
 'Datum': {'desc': 'Datum reference for the elevation fields (e.g. NAVD88; WGS84)',
  'require_field': 'O',
  'data_type': 'varchar(20)',
  'default_value': "n/a"},
 'GroundElevation': {'desc': 'Flood or Windstorm - Elevation of the local ground surface at the building at this location. This field represents the elevation of the grade (local ground surface) with respect to the datum (e.g. NAVD88).',
  'require_field': 'O',
  'data_type': 'float',
  'default_value': '-999'},
 'GroundElevationUnit': {'desc': 'Code for the unit of measure used to express the GroundElevation',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '1'},
 'Tank': {'desc': 'Code that indicates if there are rooftop tanks on the adjoining higher buildings',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'Redundancy': {'desc': 'Indicates whether there are multiple lateral load resisting elements, such as frames or shear walls',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'InternalPartition': {'desc': 'Interior wall partitions or chimneys made from URM',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'ExternalDoors': {'desc': 'Wind resistant doors, doors with a certain rating of hurricane protection',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'Torsion': {'desc': 'Code that represents the layout of structural elements that can lead to torsional loads',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'MechanicalEquipmentSide': {'desc': 'Mechanical or electrical equipment at the side',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'ContentsWindVuln': {'desc': 'Contents relative vulnerability to windstorm or tornado',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'ContentsFloodVuln': {'desc': 'Contents relative vulnerability to flood',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'ContentsQuakeVuln': {'desc': 'Contents relative vulnerability to earthquake',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'SmallDebris': {'desc': 'Code that identifies whether small debris are present within 200 meters of the structure',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'FloorsOccupied': {'desc': 'Number of floors in the building that are occupied (separated by semi-colons). Each floor occupied is separated by a semi-colon. Ranges are not accepted. 0 = ground floor, -1 = first level of basement, -2 = second level of basement; 1 = first floor, 2 = second floor, etc.',
  'require_field': 'O',
  'data_type': 'varchar(255)',
  'default_value': "n/a"},
 'FloodDefenseHeight': {'desc': 'Height of any site specific flood defenses protecting the property with respect to local ground elevation (NOT to datum).',
  'require_field': 'O',
  'data_type': 'float',
  'default_value': '-999'},
 'FloodDefenseHeightUnit': {'desc': 'Code for the unit of measure used to express the FloodDefenseHeight',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '1'},
 'FloodDebrisResilience': {'desc': 'Shows if building is vulnerable to floating debris',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'BaseFloodElevation': {'desc': 'Water surface elevation (relative to datum - this is NOT a flood depth) corresponding to a flood having a 1% probability of being equaled or exceeded in a given year. A value of -999 for this field represents unknown/default.',
  'require_field': 'O',
  'data_type': 'float',
  'default_value': '-999'},
 'BaseFloodElevationUnit': {'desc': 'Code for the unit of measure used to express the BaseFloodElevation',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '1'},
 'BuildingHeight': {'desc': 'Total height of the structure',
  'require_field': 'O',
  'data_type': 'float',
  'default_value': '-999'},
 'BuildingHeightUnit': {'desc': 'Units of the BuildingHeight',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '1'},
 'BuildingValuation': {'desc': 'Field for third party valuation data',
  'require_field': 'O',
  'data_type': 'varchar(20)',
  'default_value': "n/a"},
 'TreeExposure': {'desc': 'Secondary modifier coding density of trees adjacent to structure',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'Chimney': {'desc': 'Code that indicates if the structure has a chimney and, if so, the height of the chimney',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'BuildingType': {'desc': 'Building type (e.g. detached, terraced, etc)',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'Packaging': {'desc': 'Describes the susceptibility of the packaging of a risk to the peril',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'Protection': {'desc': 'Describes the level of protection from the specific peril',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'SalvageProtection': {'desc': 'The salvage potential of a particular product',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'ValuablesStorage': {'desc': 'Where the specie element is stored',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'DaysHeld': {'desc': 'Number of days cargo is kept at port or the duration of an exhibition. Values between 0 to 1825 (up to 5 years). Default = 365.',
  'require_field': 'O',
  'data_type': 'smallint',
  'default_value': '365'},
 'BrickVeneer': {'desc': 'Code that represents the percentage of external walls that consist of brick veneer.',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'FEMACompliance': {'desc': 'Indicates whether the building is in compliance with the FEMA flood zone requirements in both design and construction',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'CustomFloodSOP': {'desc': 'Standard of flood protection return period; values from 0-10,000',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'CustomFloodZone': {'desc': 'User-defined flood zone',
  'require_field': 'O',
  'data_type': 'varchar(20)',
  'default_value': "n/a"},
 'MultiStoryHall': {'desc': 'Code that indicates if the building has a multi-story hall',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'BuildingExteriorOpening': {'desc': 'Code that represents the percentage of exterior walls that are open (i.e. have windows or doors)',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'ServiceEquipmentProtection': {'desc': 'Code that indicates whether the service equipment is protected from flood',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'TallOneStory': {'desc': 'The height of the taller than usual one-story building (e.g. gymnasium, auditorium, church, etc.)',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'TerrainRoughness': {'desc': 'Terrain conditions around the building.',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': '0'},
 'NumberOfEmployees': {'desc': 'Number of employees',
  'require_field': 'O',
  'data_type': 'int',
  'default_value': "n/a"},
 'Payroll': {'desc': 'Total payroll',
  'require_field': 'O',
  'data_type': 'int',
  'default_value': "n/a"}}

OED_ACCOUNT_COLS = {'PortNumber': {'desc': 'Portfolio number',
  'require_field': 'R',
  'data_type': 'varchar(20)',
  'default_value': "n/a"},
 'PortName': {'desc': 'Portfolio name',
  'require_field': 'O',
  'data_type': 'varchar(40)',
  'default_value': "n/a"},
 'PortNotes': {'desc': 'Portfolio notes, longer description than allowed in portfolio name',
  'require_field': 'O',
  'data_type': 'varchar(200)',
  'default_value': "n/a"},
 'AccNumber': {'desc': 'Account number',
  'require_field': 'R',
  'data_type': 'nvarchar(40)',
  'default_value': "n/a"},
 'AccName': {'desc': 'Account name',
  'require_field': 'O',
  'data_type': 'nvarchar(100)',
  'default_value': "n/a"},
 'AccGroup': {'desc': 'Account group, could use to group multiple accounts (e.g. for binders)',
  'require_field': 'O',
  'data_type': 'varchar(40)',
  'default_value': "n/a"},
 'AccStatus': {'desc': 'Account status. Aside from predefined values, you can use other single character values for user specific purposes',
  'require_field': 'O',
  'data_type': 'char(1)',
  'default_value': "n/a"},
 'ExpiringAccNumber': {'desc': 'Expiring account number',
  'require_field': 'O',
  'data_type': 'nvarchar(40)',
  'default_value': "n/a"},
 'CedantName': {'desc': 'Cedant name (defined at account level)',
  'require_field': 'O',
  'data_type': 'varchar(40)',
  'default_value': "n/a"},
 'AccCurrency': {'desc': 'Account currency',
  'require_field': 'R',
  'data_type': 'char(3)',
  'default_value': "n/a"},
 'AccUserDef1': {'desc': 'Account user defined field 1',
  'require_field': 'O',
  'data_type': 'varchar(20)',
  'default_value': "n/a"},
 'AccUserDef2': {'desc': 'Account user defined field 2',
  'require_field': 'O',
  'data_type': 'varchar(20)',
  'default_value': "n/a"},
 'AccUserDef3': {'desc': 'Account user defined field 3',
  'require_field': 'O',
  'data_type': 'varchar(20)',
  'default_value': "n/a"},
 'AccUserDef4': {'desc': 'Account user defined field 4',
  'require_field': 'O',
  'data_type': 'varchar(20)',
  'default_value': "n/a"},
 'AccUserDef5': {'desc': 'Account user defined field 5',
  'require_field': 'O',
  'data_type': 'varchar(20)',
  'default_value': "n/a"},
 'FlexiAccZZZ': {'desc': 'Flexible field that is stored in FlexiAcc table in ModifierName = ZZZ',
  'require_field': 'O',
  'data_type': 'varchar(40)',
  'default_value': "n/a"},
 'AccPeril': {'desc': 'Perils for account financial terms',
  'require_field': 'CR',
  'data_type': 'varchar(250)',
  'default_value': "n/a"},
 'AccDedCode1Building': {'desc': 'Account building deductible code',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'AccDedType1Building': {'desc': 'Account building deductible type',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'AccDed1Building': {'desc': 'Account building deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'AccMinDed1Building': {'desc': 'Account minimum building deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'AccMaxDed1Building': {'desc': 'Account maximum building deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'AccDedCode2Other': {'desc': 'Account other building deductible code',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'AccDedType2Other': {'desc': 'Account other building deductible type',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'AccDed2Other': {'desc': 'Account other building deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'AccMinDed2Other': {'desc': 'Account minimum other building deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'AccMaxDed2Other': {'desc': 'Account maximum other building deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'AccDedCode3Contents': {'desc': 'Account contents deductible code',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'AccDedType3Contents': {'desc': 'Account contents deductible type',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'AccDed3Contents': {'desc': 'Account contents deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'AccMinDed3Contents': {'desc': 'Account minimum contents deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'AccMaxDed3Contents': {'desc': 'Account maximum contents deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'AccDedCode4BI': {'desc': 'Account BI deductible code',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'AccDedType4BI': {'desc': 'Account BI deductible type',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'AccDed4BI': {'desc': 'Account BI deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'AccMinDed4BI': {'desc': 'Account minimum BI deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'AccMaxDed4BI': {'desc': 'Account maximum BI deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'AccDedCode5PD': {'desc': 'Account PD deductible code',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'AccDedType5PD': {'desc': 'Account PD deductible type',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'AccDed5PD': {'desc': 'Account PD deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'AccMinDed5PD': {'desc': 'Account minimum PD deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'AccMaxDed5PD': {'desc': 'Account maximum PD deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'AccDedCode6All': {'desc': 'Account blanket deductible code',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'AccDedType6All': {'desc': 'Account blanket deductible type',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'AccDed6All': {'desc': 'Account blanket deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'AccMinDed6All': {'desc': 'Account minimum blanket deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'AccMaxDed6All': {'desc': 'Account maximum blanket deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'AccLimitCode1Building': {'desc': 'Account building limit code',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'AccLimitType1Building': {'desc': 'Account building limit type',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'AccLimit1Building': {'desc': 'Account building limit',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'AccLimitCode2Other': {'desc': 'Account other building limit code',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'AccLimitType2Other': {'desc': 'Account other building limit type',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'AccLimit2Other': {'desc': 'Account other building limit',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'AccLimitCode3Contents': {'desc': 'Account contents limit code',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'AccLimitType3Contents': {'desc': 'Account contents limit type',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'AccLimit3Contents': {'desc': 'Account contents limit',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'AccLimitCode4BI': {'desc': 'Account BI limit code',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'AccLimitType4BI': {'desc': 'Account BI limit type',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'AccLimit4BI': {'desc': 'Account BI limit',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'AccLimitCode5PD': {'desc': 'Account PD limit code',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'AccLimitType5PD': {'desc': 'Account PD limit type',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'AccLimit5PD': {'desc': 'Account PD limit',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'AccLimitCode6All': {'desc': 'Account blanket limit code',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'AccLimitType6All': {'desc': 'Account blanket limit type',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'AccLimit6All': {'desc': 'Account blanket limit',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'PolNumber': {'desc': 'Policy layer number',
  'require_field': 'R',
  'data_type': 'varchar(20)',
  'default_value': "n/a"},
 'PolStatus': {'desc': 'Policy layer status. Aside from predefined values, other single character values for user specific purposes can be used.',
  'require_field': 'O',
  'data_type': 'char(1)',
  'default_value': "n/a"},
 'PolInceptionDate': {'desc': 'Policy inception date - DD/MM/YYYY format',
  'require_field': 'O',
  'data_type': 'smalldatetime',
  'default_value': "n/a"},
 'PolExpiryDate': {'desc': 'Policy expiry date - DD/MM/YYYY format',
  'require_field': 'O',
  'data_type': 'smalldatetime',
  'default_value': "n/a"},
 'ProducerName': {'desc': 'Producer name (defined at policy level)',
  'require_field': 'O',
  'data_type': 'varchar(40)',
  'default_value': "n/a"},
 'Underwriter': {'desc': 'Underwriter name',
  'require_field': 'O',
  'data_type': 'varchar(40)',
  'default_value': "n/a"},
 'BranchName': {'desc': 'Branch name',
  'require_field': 'O',
  'data_type': 'varchar(20)',
  'default_value': "n/a"},
 'LOB': {'desc': 'Line of business (defined at policy level)',
  'require_field': 'O',
  'data_type': 'varchar(20)',
  'default_value': "n/a"},
 'ExpiringPolNumber': {'desc': 'Expiring policy number',
  'require_field': 'O',
  'data_type': 'varchar(20)',
  'default_value': "n/a"},
 'PolPerilsCovered': {'desc': 'Policy perils covered',
  'require_field': 'R',
  'data_type': 'varchar(250)',
  'default_value': "n/a"},
 'PolGrossPremium': {'desc': 'Policy gross premium',
  'require_field': 'O',
  'data_type': 'float',
  'default_value': '0'},
 'PolTax': {'desc': 'Policy insurance tax amount',
  'require_field': 'O',
  'data_type': 'float',
  'default_value': '0'},
 'PolBrokerage': {'desc': 'Policy brokerage amount',
  'require_field': 'O',
  'data_type': 'float',
  'default_value': '0'},
 'PolNetPremium': {'desc': 'Policy net premium',
  'require_field': 'O',
  'data_type': 'float',
  'default_value': '0'},
 'LayerNumber': {'desc': 'Layer number',
  'require_field': 'O',
  'data_type': 'int',
  'default_value': '1'},
 'LayerParticipation': {'desc': 'Insurance company share of the policy layer. Values between 0 to 1 (e.g. 12% entered as 0.12)',
  'require_field': 'O',
  'data_type': 'float',
  'default_value': '1'},
 'LayerLimit': {'desc': 'Policy layer limit',
  'require_field': 'O',
  'data_type': 'float',
  'default_value': '0'},
 'LayerAttachment': {'desc': 'Policy layer attachment point',
  'require_field': 'O',
  'data_type': 'float',
  'default_value': '0'},
 'HoursClause': {'desc': 'For perils with an inherent event duration, the insurance contract may contain an hours clause that limits the time in which claims can be added up and assigned to one event',
  'require_field': 'O',
  'data_type': 'int',
  'default_value': "n/a"},
 'PolPeril': {'desc': 'Perils for policy financial terms',
  'require_field': 'CR',
  'data_type': 'varchar(250)',
  'default_value': "n/a"},
 'PolDedCode1Building': {'desc': 'Policy building deductible code',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'PolDedType1Building': {'desc': 'Policy building deductible type',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'PolDed1Building': {'desc': 'Policy building deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'PolMinDed1Building': {'desc': 'Policy minimum building deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'PolMaxDed1Building': {'desc': 'Policy maximum building deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'PolDedCode2Other': {'desc': 'Policy other building deductible code',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'PolDedType2Other': {'desc': 'Policy other building deductible type',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'PolDed2Other': {'desc': 'Policy other building deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'PolMinDed2Other': {'desc': 'Policy minimum other building deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'PolMaxDed2Other': {'desc': 'Policy maximum other building deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'PolDedCode3Contents': {'desc': 'Policy contents deductible code',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'PolDedType3Contents': {'desc': 'Policy contents deductible type',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'PolDed3Contents': {'desc': 'Policy contents deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'PolMinDed3Contents': {'desc': 'Policy minimum contents deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'PolMaxDed3Contents': {'desc': 'Policy maximum contents deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'PolDedCode4BI': {'desc': 'Policy BI deductible code',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'PolDedType4BI': {'desc': 'Policy BI deductible type',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'PolDed4BI': {'desc': 'Policy BI deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'PolMinDed4BI': {'desc': 'Policy minimum BI deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'PolMaxDed4BI': {'desc': 'Policy maximum BI deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'PolDedCode5PD': {'desc': 'Policy PD deductible code',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'PolDedType5PD': {'desc': 'Policy PD deductible type',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'PolDed5PD': {'desc': 'Policy PD deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'PolMinDed5PD': {'desc': 'Policy minimum PD deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'PolMaxDed5PD': {'desc': 'Policy maximum PD deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'PolDedCode6All': {'desc': 'Policy blanket deductible code',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'PolDedType6All': {'desc': 'Policy blanket deductible type',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'PolDed6All': {'desc': 'Policy blanket deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'PolMinDed6All': {'desc': 'Policy minimum blanket deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'PolMaxDed6All': {'desc': 'Policy maximum blanket deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'PolLimitCode1Building': {'desc': 'Policy building limit code',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'PolLimitType1Building': {'desc': 'Policy building limit type',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'PolLimit1Building': {'desc': 'Policy building limit',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'PolLimitCode2Other': {'desc': 'Policy other building limit code',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'PolLimitType2Other': {'desc': 'Policy other building limit type',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'PolLimit2Other': {'desc': 'Policy other building limit',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'PolLimitCode3Contents': {'desc': 'Policy contents limit code',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'PolLimitType3Contents': {'desc': 'Policy contents limit type',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'PolLimit3Contents': {'desc': 'Policy contents limit',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'PolLimitCode4BI': {'desc': 'Policy BI limit code',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'PolLimitType4BI': {'desc': 'Policy BI limit type',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'PolLimit4BI': {'desc': 'Policy BI limit',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'PolLimitCode5PD': {'desc': 'Policy PD limit code',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'PolLimitType5PD': {'desc': 'Policy PD limit type',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'PolLimit5PD': {'desc': 'Policy PD limit',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'PolLimitCode6All': {'desc': 'Policy blanket limit code (annual aggregate only)',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'PolLimitType6All': {'desc': 'Policy blanket limit type',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'PolLimit6All': {'desc': 'Policy blanket limit',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'StepFunctionName': {'desc': 'Step function name',
  'require_field': 'CR',
  'data_type': 'varchar(30)',
  'default_value': "n/a"},
 'StepTriggerType': {'desc': 'Code that represents how, and for which coverages, pay-outs are triggered.',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': "n/a"},
 'StepNumber': {'desc': 'Number between 1 and 7 that is used to sort the step function in the correct order.',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': "n/a"},
 'StartTriggerBuilding': {'desc': 'Starting value of the building damage range over which the corresponding pay-out(s) should be made.',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'EndTriggerBuilding': {'desc': 'Ending value of the building damage range over which the corresponding pay-out(s) should be made.',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'DeductibleBuilding': {'desc': 'Building deductible that can be used, for example, to account for fire policies before applying step functions.',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'PayOutBuilding': {'desc': 'Pay-out that covers building gross losses for this step.',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'StartTriggerContent': {'desc': 'Starting value of the content damage range over which the corresponding pay-out(s) should be made.',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'EndTriggerContent': {'desc': 'Ending value of the content damage range over which the corresponding pay-out(s) should be made.',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'DeductibleContent': {'desc': 'Content deductible that can be used, for example, to account for fire policies before applying step functions.',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'PayOutContent': {'desc': 'Pay-out that covers content gross losses for this step.',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'StartTriggerBuildingContent': {'desc': 'Starting value of the building and content damage range over which the corresponding pay-out(s) should be made.',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'EndTriggerBuildingContent': {'desc': 'Ending value of the building and content damage range over which the corresponding pay-out(s) should be made.',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'DeductibleBuildingContent': {'desc': 'Building and content deductible that can be used, for example, to account for fire policies before applying step functions.',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'PayOutBuildingContent': {'desc': 'Pay-out that covers building and content gross losses for this step.',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'MinimumTIV': {'desc': 'Minimum replacement value for which pay-outs to the corresponding damage range will be allowed.',
  'require_field': 'O',
  'data_type': 'float',
  'default_value': '0'},
 'ScaleFactor': {'desc': 'Percentage factor used to scale calculated losses. This value, entered as a decimal, should be the same for all steps for a policy contract and must be a value >0 and ≤1. For example, 0.12 for 12%.',
  'require_field': 'O',
  'data_type': 'float',
  'default_value': '1'},
 'IsLimitAtDamage': {'desc': 'Indicates whether the pay-out is limited by the actual ground-up loss.',
  'require_field': 'O',
  'data_type': 'float',
  'default_value': '0'},
 'PolUserDef1': {'desc': 'Policy user defined field',
  'require_field': 'O',
  'data_type': 'varchar(20)',
  'default_value': "n/a"},
 'PolUserDef2': {'desc': 'Policy user defined field',
  'require_field': 'O',
  'data_type': 'varchar(20)',
  'default_value': "n/a"},
 'PolUserDef3': {'desc': 'Policy user defined field',
  'require_field': 'O',
  'data_type': 'varchar(20)',
  'default_value': "n/a"},
 'PolUserDef4': {'desc': 'Policy user defined field',
  'require_field': 'O',
  'data_type': 'varchar(20)',
  'default_value': "n/a"},
 'PolUserDef5': {'desc': 'Policy user defined field',
  'require_field': 'O',
  'data_type': 'varchar(20)',
  'default_value': "n/a"},
 'FlexiPolZZZ': {'desc': 'Flexible field that is stored in FlexiPol table in ModifierName = ZZZ',
  'require_field': 'O',
  'data_type': 'varchar(40)',
  'default_value': "n/a"},
 'CondNumber': {'desc': 'Condition number (must be the same if condition repeats on several policy layers)',
  'require_field': 'CR',
  'data_type': 'int',
  'default_value': "n/a"},
 'CondName': {'desc': 'Condition name (must be the same if condition repeats on several policy layers). Description that relates to CondNumber.',
  'require_field': 'CR',
  'data_type': 'varchar(40)',
  'default_value': "n/a"},
 'CondPeril': {'desc': 'Perils for condition financial terms',
  'require_field': 'CR',
  'data_type': 'varchar(250)',
  'default_value': "n/a"},
 'CondDedCode1Building': {'desc': 'Special condition building deductible code',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'CondDedType1Building': {'desc': 'Special condition building deductible type',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'CondDed1Building': {'desc': 'Special condition building deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'CondMinDed1Building': {'desc': 'Special condition minimum building deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'CondMaxDed1Building': {'desc': 'Special condition maximum building deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'CondDedCode2Other': {'desc': 'Special condition other building deductible code',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'CondDedType2Other': {'desc': 'Special condition other building deductible type',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'CondDed2Other': {'desc': 'Special condition other building deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'CondMinDed2Other': {'desc': 'Special condition minimum other building deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'CondMaxDed2Other': {'desc': 'Special condition maximum other building deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'CondDedCode3Contents': {'desc': 'Special condition contents deductible code',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'CondDedType3Contents': {'desc': 'Special condition contents deductible type',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'CondDed3Contents': {'desc': 'Special condition contents deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'CondMinDed3Contents': {'desc': 'Special condition minimum contents deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'CondMaxDed3Contents': {'desc': 'Special condition maximum contents deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'CondDedCode4BI': {'desc': 'Special condition BI deductible code',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'CondDedType4BI': {'desc': 'Special condition BI deductible type',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'CondDed4BI': {'desc': 'Special condition BI deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'CondMinDed4BI': {'desc': 'Special condition minimum BI deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'CondMaxDed4BI': {'desc': 'Special condition maximum BI deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'CondDedCode5PD': {'desc': 'Special condition PD deductible code',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'CondDedType5PD': {'desc': 'Special condition PD deductible type',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'CondDed5PD': {'desc': 'Special condition PD deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'CondMinDed5PD': {'desc': 'Special condition minimum PD deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'CondMaxDed5PD': {'desc': 'Special condition maximum PD deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'CondDedCode6All': {'desc': 'Special condition blanket deductible code',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'CondDedType6All': {'desc': 'Special condition blanket deductible type',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'CondDed6All': {'desc': 'Special condition blanket deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'CondMinDed6All': {'desc': 'Special condition minimum blanket deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'CondMaxDed6All': {'desc': 'Special condition maximum blanket deductible',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'CondLimitCode1Building': {'desc': 'Special condition building limit code',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'CondLimitType1Building': {'desc': 'Special condition building limit type',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'CondLimit1Building': {'desc': 'Special condition building limit',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'CondLimitCode2Other': {'desc': 'Special condition other building limit code',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'CondLimitType2Other': {'desc': 'Special condition other building limit type',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'CondLimit2Other': {'desc': 'Special condition other building limit',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'CondLimitCode3Contents': {'desc': 'Special condition contents limit code',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'CondLimitType3Contents': {'desc': 'Special condition contents limit type',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'CondLimit3Contents': {'desc': 'Special condition contents limit',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'CondLimitCode4BI': {'desc': 'Special condition BI limit code',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'CondLimitType4BI': {'desc': 'Special condition BI limit type',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'CondLimit4BI': {'desc': 'Special condition BI limit',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'CondLimitCode5PD': {'desc': 'Special condition PD limit code',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'CondLimitType5PD': {'desc': 'Special condition PD limit type',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'CondLimit5PD': {'desc': 'Special condition PD limit',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'},
 'CondLimitCode6All': {'desc': 'Special condition blanket limit code',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'CondLimitType6All': {'desc': 'Special condition blanket limit type',
  'require_field': 'CR',
  'data_type': 'tinyint',
  'default_value': '0'},
 'CondLimit6All': {'desc': 'Special condition blanket limit',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '0'}}



OED_REINSINFO_COLS = {'ReinsNumber': {'desc': 'Reinsurance number',
  'require_field': 'R',
  'data_type': 'int',
  'default_value': "n/a"},
 'ReinsName': {'desc': 'Reinsurance name',
  'require_field': 'O',
  'data_type': 'varchar(30)',
  'default_value': "n/a"},
 'ReinsLayerNumber': {'desc': 'Reinsurance layer for information / ordering purposes',
  'require_field': 'O',
  'data_type': 'int',
  'default_value': "n/a"},
 'ReinsPeril': {'desc': 'Perils for reinsurance financial terms',
  'require_field': 'R',
  'data_type': 'varchar(250)',
  'default_value': "n/a"},
 'ReinsInceptionDate': {'desc': 'Reinsurance inception date - DD/MM/YYYY format',
  'require_field': 'O',
  'data_type': 'smalldatetime',
  'default_value': "n/a"},
 'ReinsExpiryDate': {'desc': 'Reinsurance expiry date - DD/MM/YYYY format',
  'require_field': 'O',
  'data_type': 'smalldatetime',
  'default_value': "n/a"},
 'CededPercent': {'desc': 'Reinsurance ceded percentage. Used mainly in surplus treaties. Applies before other reinsurance terms. Values between 0 to 1 (e.g. 12% entered as 0.12)',
  'require_field': 'O',
  'data_type': 'float',
  'default_value': '1.0'},
 'RiskLimit': {'desc': 'Reinsurance per-risk limit',
  'require_field': 'O',
  'data_type': 'float',
  'default_value': '0'},
 'RiskAttachment': {'desc': 'Reinsurance per-risk attachment point',
  'require_field': 'O',
  'data_type': 'float',
  'default_value': '0'},
 'OccLimit': {'desc': 'Reinsurance occurrence limit',
  'require_field': 'O',
  'data_type': 'float',
  'default_value': '0'},
 'OccAttachment': {'desc': 'Reinsurance per occurrence attachment',
  'require_field': 'O',
  'data_type': 'float',
  'default_value': '0'},
 'OccFranchiseDed': {'desc': 'Reinsurance franchise deductible',
  'require_field': 'O',
  'data_type': 'float',
  'default_value': '0'},
 'OccReverseFranchise': {'desc': 'Reinsurance reverse franchise - a value of loss that, if exceeded, results in no payment being made for this event from the reinsurer to insurer.',
  'require_field': 'O',
  'data_type': 'float',
  'default_value': '0'},
 'AggLimit': {'desc': 'Maximum amount payable under this treaty during the AggPeriod',
  'require_field': 'O',
  'data_type': 'float',
  'default_value': '0'},
 'AggAttachment': {'desc': 'The aggregate monetary amount during a given AggPeriod that the resinured retains under this treaty',
  'require_field': 'O',
  'data_type': 'float',
  'default_value': '0'},
 'AggPeriod': {'desc': 'Aggregate period associated with the aggregate limits and attachments (in days). Default value = 365 (1 year)',
  'require_field': 'O',
  'data_type': 'float',
  'default_value': '365'},
 'PlacedPercent': {'desc': 'Percentage of the limit that has been placed in the reinsurance market. The main percentage used for reinsurance treaties other than surplus. Applies after other reinsurance terms. Values between 0 to 1 (e.g. 12% entered as 0.12)',
  'require_field': 'R',
  'data_type': 'float',
  'default_value': "n/a"},
 'ReinsCurrency': {'desc': 'Reinsurance currency',
  'require_field': 'R',
  'data_type': 'char(3)',
  'default_value': "n/a"},
 'InuringPriority': {'desc': 'Reinsurance inuring priority capturing the order in which reinsurance contracts apply. Treaties with lower number inuring priorities apply first.',
  'require_field': 'R',
  'data_type': 'tinyint',
  'default_value': "n/a"},
 'ReinsType': {'desc': 'Type of reinsurance contract',
  'require_field': 'R',
  'data_type': 'varchar(3)',
  'default_value': "n/a"},
 'AttachmentBasis': {'desc': 'Reinsurance attachment basis',
  'require_field': 'O',
  'data_type': 'char(2)',
  'default_value': "('LO')"},
 'Reinstatement': {'desc': 'Number of reinstatements',
  'require_field': 'O',
  'data_type': 'tinyint',
  'default_value': "n/a"},
 'ReinstatementCharge': {'desc': 'Reinstatement charge as %; semi-colon separated if different for each reinstatement (e.g. 1-free, 2-50%, 3-100% should be entered as: 0;0.5;1). If all reinstatements are the same, then just one number is sufficient (e.g. 3 reinstatements at 100% should be entered as 1)',
  'require_field': 'O',
  'data_type': 'float',
  'default_value': "n/a"},
 'ReinsPremium': {'desc': 'Reinsurance premium',
  'require_field': 'O',
  'data_type': 'float',
  'default_value': '0'},
 'DeemedPercentPlaced': {'desc': 'Deemed percent placed, used to represent notional contracts or any part of the contract being notional. For fully notional contracts, enter 1 (i.e. 100%). For partially placed contracts, enter any value between 0 and 1. For real contracts, enter 0.',
  'require_field': 'O',
  'data_type': 'float',
  'default_value': '0'},
 'ReinsFXrate': {'desc': 'Reinsurance exchange rate (as the contractual reinsurance rate can be different from the actual exchange rates used for policies and locations)',
  'require_field': 'O',
  'data_type': 'float',
  'default_value': '1'},
 'TreatyShare': {'desc': 'The percentage of a treaty that a given reinsurer may write. Values between 0 to 1 (e.g. 12% entered as 0.12).',
  'require_field': 'O',
  'data_type': 'float',
  'default_value': '1'},
 'UseReinsDates': {'desc': 'A flag to indicate if reinsurance contract dates or  policy inception / expiry dates are to be considered when calculating losses (Y) or ignored (N).',
  'require_field': 'O',
  'data_type': 'char(1)',
  'default_value': 'N'}}



OED_REINSSCOPE_COLS = {'ReinsNumber': {'desc': 'Reinsurance number to link with ReinsInfo file',
  'require_field': 'R',
  'data_type': 'int',
  'default_value': "n/a"},
 'PortNumber': {'desc': 'Portfolio number: used for defining treaty scope in the reinsurance scope file',
  'require_field': 'CR',
  'data_type': 'varchar(20)',
  'default_value': "n/a"},
 'AccNumber': {'desc': 'Account number:  used for defining treaty scope in the reinsurance scope file',
  'require_field': 'CR',
  'data_type': 'nvarchar(40)',
  'default_value': "n/a"},
 'PolNumber': {'desc': 'Policy number:  used for defining treaty scope in the reinsurance scope file',
  'require_field': 'CR',
  'data_type': 'varchar(20)',
  'default_value': "n/a"},
 'LocGroup': {'desc': 'Location group name:  used for defining treaty scope in the reinsurance scope file',
  'require_field': 'CR',
  'data_type': 'nvarchar(20)',
  'default_value': "n/a"},
 'LocNumber': {'desc': 'Location number:  used for defining treaty scope in the reinsurance scope file',
  'require_field': 'CR',
  'data_type': 'nvarchar(20)',
  'default_value': "n/a"},
 'CedantName': {'desc': 'Cedant name:  used for defining treaty scope in the reinsurance scope file',
  'require_field': 'CR',
  'data_type': 'varchar(40)',
  'default_value': "n/a"},
 'ProducerName': {'desc': 'Producer name:  used for defining treaty scope in the reinsurance scope file',
  'require_field': 'CR',
  'data_type': 'varchar(40)',
  'default_value': "n/a"},
 'LOB': {'desc': 'Line of business:  used for defining treaty scope in the reinsurance scope file',
  'require_field': 'CR',
  'data_type': 'varchar(20)',
  'default_value': "n/a"},
 'CountryCode': {'desc': 'Country code: used for defining treaty scope in the reinsurance scope file',
  'require_field': 'CR',
  'data_type': 'char(2)',
  'default_value': "n/a"},
 'ReinsTag': {'desc': 'Reinsurance tag: user defined field to for defining treaty scope in the reinsurance scope file',
  'require_field': 'CR',
  'data_type': 'varchar(20)',
  'default_value': "n/a"},
 'CededPercent': {'desc': 'Ceded percentage (for 12%, enter 0.12). Within the reinsurance scope file, CededPercent should only be entered for surplus share treaties.',
  'require_field': 'CR',
  'data_type': 'float',
  'default_value': '1.0'},
 'RiskLevel': {'desc': "Code to indicate the definition of 'risk' for the per-risk terms in this particular treaty (or portion of the treaty)",
  'require_field': 'R',
  'data_type': 'char(3)',
  'default_value': "n/a"}}
