RUNTYPE_GROUNDUP_LOSS = 'gul'
RUNTYPE_INSURED_LOSS = 'il'
RUNTYPE_REINSURANCE_LOSS = 'ri'
RUNTYPE_REINSURANCE_GROSS_LOSS = 'rl'
RUNTYPE_FULL_CORRELATION = 'fc'
RUNTYPE_LOAD_BALANCED_LOSS = 'lb'

REINSURANCE_RUNTYPES = [RUNTYPE_REINSURANCE_LOSS, RUNTYPE_REINSURANCE_GROSS_LOSS]
LOSS_RUNTYPES = [RUNTYPE_GROUNDUP_LOSS, RUNTYPE_INSURED_LOSS, RUNTYPE_REINSURANCE_LOSS]
