name: Build and Deploy Docs
on:
  push:
    branches:
      - main
      - master

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false


jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Compile package requirements.txt
        run: |
           pip install pip-tools
           pip-compile requirements.in
      - name: Install required packages
        run: | 
            pip install -r requirements.txt
            pip install furo
      - name: Build
        run: ./docs/build.sh
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './docs/build/html/'

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

      # - name: Deploy
      #   uses: JamesIves/github-pages-deploy-action@v4
      #   with:
      #     folder: ./docs/build/html
      #     repository-name: OasisLMF/OasisLMF.github.io
      #     token: ${{ secrets.BUILD_DEPLOY_TOKEN }}