name: Python package

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Package
        run: pip install --upgrade autopep8
      - name: Install autopep8
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade pip-tools
      - uses: jitterbit/get-changed-files@v1
        with:
          # Format of the steps output context.
          format: 'space-delimited' 
      - name: autopep8
        id: autopep8
        run: |
          autopep8 --diff --exit-code ${{ steps.abc.outputs.added_modified }}
      - name: Fail if autopep8 made changes
        if: steps.autopep8.outputs.exit-code == 2
        run: exit 1
