name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install ktools
        run: |
          export KTOOLS_VER=$(grep -Eo '[0-9]\.[0-9]\.[0-9]+' setup.py)
          export KTOOLS_BIN_DIR=$HOME/.local/bin
          mkdir -p $KTOOLS_BIN_DIR
          export PATH=$PATH:$KTOOLS_BIN_DIR
          wget https://github.com/OasisLMF/ktools/releases/download/v$KTOOLS_VER/Linux_x86_64.tar.gz
          tar -xvzf  Linux_x86_64.tar.gz -C $HOME/.local/bin
      - name: Install Package
        run: pip install --no-dependencies -e .
      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pip-tools tox
          
      - name: Pip Compile
        run: |
          rm -f requirements.txt
          pip-compile requirements.in -o requirements.txt  
      - name: Run tox
        run: tox -e py
