name: Version Release Branch

on:
  create:
    branches:
      - 'release/**'

jobs:
  extract_version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract_version.outputs.version }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Extract version from branch name
        id: extract_version
        run: |
          BRANCH_NAME="${{ github.ref }}"
          VERSION=$(echo "$BRANCH_NAME" | sed -n 's#.*/release/\([0-9]\+\.[0-9]\+\.[0-9]\+\)#\1#p')
          if [[ -z "$VERSION" ]]; then
            echo "No valid semantic version found. Exiting."
            exit 1
          fi
          echo "version=$VERSION" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV

  version_update:
    runs-on: ubuntu-latest
    needs: extract_version  # Fixed reference (underscore, not hyphen)
    steps:
      - name: Update version
        uses: ./.github/workflows/version.yml
        secrets: inherit
        with:
          oasislmf_version: ${{ needs.extract_version.outputs.version }}  # Fixed reference
